In [9]:
import pandas as pd
import numpy as np
# p = '/mnt/data/data_foundations_dataset/sales.csv'
df = pd.read_csv("sales.csv")
df

,order_id,date,product_id,product,category,city,quantity,unit_price,discount_pct,payment_method
0,ORD1001,2026-01-03,P101,Wireless Mouse,Accessories,Chennai,2,650.0,0.0,UPI
1,ORD1002,2026-01-04,P102,Mechanical Keyboard,Accessories,Bengaluru,1,2400.0,5.0,Card
2,ORD1003,2026-01-05,P103,USB-C Hub,Connectivity,Hyderabad,3,1250.0,10.0,UPI
3,ORD1004,2026-01-06,P104,Laptop Stand,Workspace,Chennai,2,950.0,0.0,Cash
4,ORD1005,2026-01-07,P105,Webcam,Electronics,Pune,1,3200.0,NaN,Card
5,ORD1006,2026-01-08,P101,Wireless Mouse,Accessories,Mumbai,4,650.0,5.0,UPI
6,ORD1007,2026-01-09,P106,Noise-Cancelling Headphones,Audio,Bengaluru,1,5400.0,12.0,Card
7,ORD1008,2026-01-10,P107,Portable SSD,Storage,Hyderabad,2,4100.0,0.0,UPI
8,ORD1009,2026-01-11,P102,Mechanical Keyboard,Accessories,Pune,2,2400.0,8.0,NaN
9,ORD1004,2026-01-06,P104,Laptop Stand,Workspace,Chennai,2,950.0,0.0,Cash

In [11]:
df.head()

,order_id,date,product_id,product,category,city,quantity,unit_price,discount_pct,payment_method
0,ORD1001,2026-01-03,P101,Wireless Mouse,Accessories,Chennai,2,650.0,0.0,UPI
1,ORD1002,2026-01-04,P102,Mechanical Keyboard,Accessories,Bengaluru,1,2400.0,5.0,Card
2,ORD1003,2026-01-05,P103,USB-C Hub,Connectivity,Hyderabad,3,1250.0,10.0,UPI
3,ORD1004,2026-01-06,P104,Laptop Stand,Workspace,Chennai,2,950.0,0.0,Cash
4,ORD1005,2026-01-07,P105,Webcam,Electronics,Pune,1,3200.0,NaN,Card

In [13]:
df.tail()

,order_id,date,product_id,product,category,city,quantity,unit_price,discount_pct,payment_method
5,ORD1006,2026-01-08,P101,Wireless Mouse,Accessories,Mumbai,4,650.0,5.0,UPI
6,ORD1007,2026-01-09,P106,Noise-Cancelling Headphones,Audio,Bengaluru,1,5400.0,12.0,Card
7,ORD1008,2026-01-10,P107,Portable SSD,Storage,Hyderabad,2,4100.0,0.0,UPI
8,ORD1009,2026-01-11,P102,Mechanical Keyboard,Accessories,Pune,2,2400.0,8.0,NaN
9,ORD1004,2026-01-06,P104,Laptop Stand,Workspace,Chennai,2,950.0,0.0,Cash

In [15]:
df.shape

(10, 10)

In [17]:
df.size

100

In [19]:
df.columns

Index(['order_id', 'date', 'product_id', 'product', 'category', 'city',
       'quantity', 'unit_price', 'discount_pct', 'payment_method'],
      dtype='str')

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        10 non-null     str
 1   date            10 non-null     str
 2   product_id      10 non-null     str
 3   product         10 non-null     str
 4   category        10 non-null     str
 5   city            10 non-null     str
 6   quantity        10 non-null     int64
 7   unit_price      10 non-null     float64
 8   discount_pct    9 non-null      float64
 9   payment_method  9 non-null      str
dtypes: float64(2), int64(1), str(7)
memory usage: 1.5 KB

In [23]:
df.isnull().sum()

order_id          0
date              0
product_id        0
product           0
category          0
city              0
quantity          0
unit_price        0
discount_pct      1
payment_method    1
dtype: int64

In [25]:
df.duplicated().sum()

np.int64(1)

In [27]:
df["unit_price"]

0     650.0
1    2400.0
2    1250.0
3     950.0
4    3200.0
5     650.0
6    5400.0
7    4100.0
8    2400.0
9     950.0
Name: unit_price, dtype: float64

In [33]:
a = df["unit_price"].sum()
print("Sum of unit_price: " , a)

Sum of unit_price:  21950.0

In [35]:
a = df["unit_price"].mean()
print("mean of unit_price: " , a)

mean of unit_price:  2195.0

In [38]:
a = df["unit_price"].median()
print("median of unit_price: " , a)

median of unit_price:  1825.0

In [40]:
a = df["unit_price"].min()
print("Min of unit_price: " , a)

Min of unit_price:  650.0

In [42]:
a = df["unit_price"].max()
print("max of unit_price: " , a)

max of unit_price:  5400.0

In [44]:
a = df["unit_price"].std()
print("standard devaiation of unit_price: " , a)

standard devaiation of unit_price:  1624.8846112878293

In [50]:
# creating a new column and calcaulating statsitcs
df["discount_pct"] = df["discount_pct"].fillna(0)
df["revenue"] = (df["quantity"] * df["unit_price"] * (1 - df["discount_pct"] / 100))
df[["product","quantity","unit_price","discount_pct","revenue"]]

                       product  quantity  unit_price  discount_pct  revenue
0               Wireless Mouse         2       650.0           0.0   1300.0
1          Mechanical Keyboard         1      2400.0           5.0   2280.0
2                    USB-C Hub         3      1250.0          10.0   3375.0
3                 Laptop Stand         2       950.0           0.0   1900.0
4                       Webcam         1      3200.0           0.0   3200.0
5               Wireless Mouse         4       650.0           5.0   2470.0
6  Noise-Cancelling Headphones         1      5400.0          12.0   4752.0
7                 Portable SSD         2      4100.0           0.0   8200.0
8          Mechanical Keyboard         2      2400.0           8.0   4416.0
9                 Laptop Stand         2       950.0           0.0   1900.0

In [54]:
tot_revenue = df["revenue"].sum()
maxx = df["revenue"].max()
minn = df["revenue"].min()
meann = df["revenue"].mean()

print("SUM ", tot_revenue)
print("MIN ", minn)
print("MAX ", maxx)
print("MEAN ", meann)

SUM  33793.0
MIN  1300.0
MAX  8200.0
MEAN  3379.3

In [56]:

df.groupby("city")["revenue"].sum().sort_values(ascending=False)

city
Hyderabad    11575.0
Pune          7616.0
Bengaluru     7032.0
Chennai       5100.0
Mumbai        2470.0
Name: revenue, dtype: float64

In [58]:
df["date"] = pd.to_datetime(df["date"])

daily_revenue = df.groupby("date")["revenue"].sum()

print(daily_revenue)

date
2026-01-03    1300.0
2026-01-04    2280.0
2026-01-05    3375.0
2026-01-06    3800.0
2026-01-07    3200.0
2026-01-08    2470.0
2026-01-09    4752.0
2026-01-10    8200.0
2026-01-11    4416.0
Name: revenue, dtype: float64

In [62]:
# Filter Chennai sales
df[df["city"] == "Chennai"]

# Filter Accessories
df[df["category"] == "Accessories"]

# Filter Wireless Mouse sales
df[df["product"] == "Wireless Mouse"]

# Revenue greater than 2000
df[df["revenue"] > 2000]

,order_id,date,product_id,product,category,city,quantity,unit_price,discount_pct,payment_method,revenue
1,ORD1002,2026-01-04,P102,Mechanical Keyboard,Accessories,Bengaluru,1,2400.0,5.0,Card,2280.0
2,ORD1003,2026-01-05,P103,USB-C Hub,Connectivity,Hyderabad,3,1250.0,10.0,UPI,3375.0
4,ORD1005,2026-01-07,P105,Webcam,Electronics,Pune,1,3200.0,0.0,Card,3200.0
5,ORD1006,2026-01-08,P101,Wireless Mouse,Accessories,Mumbai,4,650.0,5.0,UPI,2470.0
6,ORD1007,2026-01-09,P106,Noise-Cancelling Headphones,Audio,Bengaluru,1,5400.0,12.0,Card,4752.0
7,ORD1008,2026-01-10,P107,Portable SSD,Storage,Hyderabad,2,4100.0,0.0,UPI,8200.0
8,ORD1009,2026-01-11,P102,Mechanical Keyboard,Accessories,Pune,2,2400.0,8.0,NaN,4416.0

In [84]:
import csv
import time
import numpy as np

# loading the data
with open("sales.csv", newline="") as f:
    data = list(csv.DictReader(f))
# verifiying the data
# print("Rows:", len(data))
# print("Columns:", list(data[0].keys()))

# finding duplicate orders
seen = set()
duplicates = []
for row in data:
    if row["order_id"] in seen:
        duplicates.append(row["order_id"])
    seen.add(row["order_id"])
print("------------------------------------------------------------------finding duplicates------------------------------------------------------------------------")

print("Duplicate orders:", duplicates)
print("with Duplicate orders tot length:", len(data))

# removeing duplicated order id
seen = set()
unique_data = []

for row in data:
    if row["order_id"] not in seen:
        unique_data.append(row)
    seen.add(row["order_id"])
print("------------------------------------------------------------------removed duplicates & serialized data------------------------------------------------------------------------")

print("Duplicate orders serialized : ", len(unique_data))

#clean data and Calculating revenue
for row in unique_data:
    row["quantity"] = int(row["quantity"])
    row["unit_price"] = float(row["unit_price"])
    row["discount_pct"] = float(row["discount_pct"] or 0)
    row["payment_method"] = row["payment_method"] or "Unknown"

    row["revenue"] = (row["quantity"] * row["unit_price"] * (1 - row["discount_pct"] / 100 ))
    
print("------------------------------------------------------------------clean data and Calculating revenue------------------------------------------------------------------------")

print(unique_data[:3])

print("------------------------------------------------------------------Without numpy------------------------------------------------------------------------")
# descriptive analysis without numpy
revenue = [row["revenue"] for row in unique_data]
n=len(revenue)
print("total_length ", len(revenue))
print("total_sum " , sum(revenue))
print("max_num" , max(revenue))
print("min_num", min(revenue))
print("average",sum(revenue)/n)
print("range", max(revenue) - min(revenue))

# descriptive analysis with numpy
arr = np.array(revenue)
print("------------------------------------------------------------------With numpy------------------------------------------------------------------------")

print("count:", arr.size)
print("total:", np.sum(arr))
print("average:", np.mean(arr))
print("median:", np.median(arr))
print("minimum:", np.min(arr))
print("maximum:", np.max(arr))
print("range:", np.ptp(arr))
print("std:", np.std(arr))

print("------------------------------------------------------------------revenue by product,city,category------------------------------------------------------------------------")

for col in ["product", "city", "category"]:
    result = {}

    for row in unique_data:
        key = row[col]
        result[key] = result.get(key, 0) + row["revenue"]

    print(f"\nRevenue by {col}:")
    print(sorted(result.items(), key=lambda x: x[1], reverse=True))

print("------------------------------------------------------------------Comparission of execution time------------------------------------------------------------------------")

start = time.perf_counter()
sum(revenue)
python_time = time.perf_counter() - start

start = time.perf_counter()
np.sum(arr)
numpy_time = time.perf_counter() - start

print("Pure Python time:", python_time)
print("NumPy time:", numpy_time)

------------------------------------------------------------------finding duplicates------------------------------------------------------------------------
Duplicate orders: ['ORD1004']
with Duplicate orders tot length: 10
------------------------------------------------------------------removed duplicates & serialized data------------------------------------------------------------------------
Duplicate orders serialized :  9
------------------------------------------------------------------clean data and Calculating revenue------------------------------------------------------------------------
[{'order_id': 'ORD1001', 'date': '2026-01-03', 'product_id': 'P101', 'product': 'Wireless Mouse', 'category': 'Accessories', 'city': 'Chennai', 'quantity': 2, 'unit_price': 650.0, 'discount_pct': 0.0, 'payment_method': 'UPI', 'revenue': 1300.0}, {'order_id': 'ORD1002', 'date': '2026-01-04', 'product_id': 'P102', 'product': 'Mechanical Keyboard', 'category': 'Accessories', 'city': 'Bengaluru', 'quantity': 1, 'unit_price': 2400.0, 'discount_pct': 5.0, 'payment_method': 'Card', 'revenue': 2280.0}, {'order_id': 'ORD1003', 'date': '2026-01-05', 'product_id': 'P103', 'product': 'USB-C Hub', 'category': 'Connectivity', 'city': 'Hyderabad', 'quantity': 3, 'unit_price': 1250.0, 'discount_pct': 10.0, 'payment_method': 'UPI', 'revenue': 3375.0}]
------------------------------------------------------------------Without numpy------------------------------------------------------------------------
total_length  9
total_sum  31893.0
max_num 8200.0
min_num 1300.0
average 3543.6666666666665
range 6900.0
------------------------------------------------------------------With numpy------------------------------------------------------------------------
count: 9
total: 31893.0
average: 3543.6666666666665
median: 3200.0
minimum: 1300.0
maximum: 8200.0
range: 6900.0
std: 1958.863729592008
------------------------------------------------------------------revenue by product,city,category------------------------------------------------------------------------

Revenue by product:
[('Portable SSD', 8200.0), ('Mechanical Keyboard', 6696.0), ('Noise-Cancelling Headphones', 4752.0), ('Wireless Mouse', 3770.0), ('USB-C Hub', 3375.0), ('Webcam', 3200.0), ('Laptop Stand', 1900.0)]

Revenue by city:
[('Hyderabad', 11575.0), ('Pune', 7616.0), ('Bengaluru', 7032.0), ('Chennai', 3200.0), ('Mumbai', 2470.0)]

Revenue by category:
[('Accessories', 10466.0), ('Storage', 8200.0), ('Audio', 4752.0), ('Connectivity', 3375.0), ('Electronics', 3200.0), ('Workspace', 1900.0)]
Pure Python time: 5.447899820865132e-05
NumPy time: 6.369800030370243e-05