In [16]:
import pandas as pd

#inspect the dataset
df = pd.read_csv("sales_dirty.csv")
print("------------------------------data types and total rows of non null value data------------------------------------------")
df.info()
print("------------------------------gives all the staustical data of mean count std max everyhitng that needs for computation or analaysis ------------------------------------------")
print(df.describe())
print("------------------------------gives all the columns that are present in the csv or dataset ------------------------------------------")
print(df.columns)
print("------------------------------total count of null values on each column ------------------------------------------")
print(df.isnull().sum())

------------------------------data types and total rows of non null value data------------------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    14 non-null     str
 1   Product    14 non-null     str
 2   City       13 non-null     str
 3   Quantity   13 non-null     str
 4   UnitPrice  14 non-null     int64
 5   OrderDate  14 non-null     str
dtypes: int64(1), str(5)
memory usage: 804.0 bytes
------------------------------gives all the staustical data of mean count std max everyhitng that needs for computation or analaysis ------------------------------------------
           UnitPrice
count      14.000000
mean    85121.357143
std    264070.916148
min       500.000000
25%      1350.000000
50%      7500.000000
75%     39625.000000
max    999999.000000
------------------------------gives all the columns that are present in the csv or dataset ------------------------------------------
Index(['OrderID', 'Product', 'City', 'Quantity', 'UnitPrice', 'OrderDate'],
      dtype='str')
------------------------------total count of null values on each column ------------------------------------------
OrderID      0
Product      0
City         1
Quantity     1
UnitPrice    0
OrderDate    0
dtype: int64

In [27]:
#identify and remove duplicates

print(df.duplicated().sum())
print(df[df.duplicated()])

df = df.drop_duplicates()
df

0
Empty DataFrame
Columns: [OrderID, Product, City, Quantity, UnitPrice, OrderDate]
Index: []

   OrderID     Product       City Quantity  UnitPrice   OrderDate
0    O1001     Laptop     Chennai        2      50000  2026-10-01
1    O1002       Mouse    chennai        5        500  2026-10-02
2    O1003    Keyboard    CHENNAI        3       1200  2026-10-03
3    O1004     Monitor  Bengaluru        2       8500  2026-10-04
4    O1005      Laptop    Chennai      NaN      52000  2026-10-05
5    O1006       Mouse  Hyderabad        4        500  2026-10-06
6    O1007    Keyboard  Bengaluru        2       1200  2026-10-07
7    O1008     Monitor    chennai        3       8500  2026-10-08
9    O1010      Laptop  Hyderabad        2      50000  not-a-date
10   O1011  Headphones  Bengaluru      two       2500  2026-10-11
11   O1012      Webcam        NaN        4       1800  2026-10-12
12   O1013        Desk    Chennai        1     999999  2026-10-13
13   O1014       Chair  Hyderabad        3       6500  2026-10-14

In [35]:
# Standardize product and city names
df["Product"] = df["Product"].str.strip().str.title()
df["City"] = df["City"].str.strip().str.title()
print("------------------------------Standardized value for products no inconsistent data for product column------------------------------------------")
print(df["product"])
print("------------------------------Standardized value for products no inconsistent data for city column------------------------------------------")

print(df["City"])

------------------------------Standardized value for products no inconsistent data for product column------------------------------------------
0         Laptop
1          Mouse
2       Keyboard
3        Monitor
4         Laptop
5          Mouse
6       Keyboard
7        Monitor
9         Laptop
10    Headphones
11        Webcam
12          Desk
13         Chair
Name: product, dtype: str
------------------------------Standardized value for products no inconsistent data for city column------------------------------------------
0       Chennai
1       Chennai
2       Chennai
3     Bengaluru
4       Chennai
5     Hyderabad
6     Bengaluru
7       Chennai
9     Hyderabad
10    Bengaluru
11          NaN
12      Chennai
13    Hyderabad
Name: City, dtype: str

In [40]:
# convert data into a proper data type
df["OrderDate"] = pd.to_datetime(df["OrderDate"],errors="coerce") 
print(df[["OrderDate"]])
print(df["OrderDate"].dtype)

    OrderDate
0  2026-10-01
1  2026-10-02
2  2026-10-03
3  2026-10-04
4  2026-10-05
5  2026-10-06
6  2026-10-07
7  2026-10-08
9         NaT
10 2026-10-11
11 2026-10-12
12 2026-10-13
13 2026-10-14
datetime64[us]

In [46]:
# convert numeric columns
df["Quantity"] = pd.to_numeric(df["Quantity"], errors = "coerce")
df["UnitPrice"] = pd.to_numeric(df["UnitPrice"], errors = "coerce")
print(df["Quantity"])

0     2.0
1     5.0
2     3.0
3     2.0
4     NaN
5     4.0
6     2.0
7     3.0
9     2.0
10    NaN
11    4.0
12    1.0
13    3.0
Name: Quantity, dtype: float64

In [50]:
# handle missing values
df["Quantity"] = df["Quantity"].fillna(
    df["Quantity"].median()
)

df["UnitPrice"] = df["UnitPrice"].fillna(
    df["UnitPrice"].median()
)

df["City"] = df["City"].fillna("Unknown")

print(df["Quantity"])
print(df["City"])

0     2.0
1     5.0
2     3.0
3     2.0
4     3.0
5     4.0
6     2.0
7     3.0
9     2.0
10    3.0
11    4.0
12    1.0
13    3.0
Name: Quantity, dtype: float64
0       Chennai
1       Chennai
2       Chennai
3     Bengaluru
4       Chennai
5     Hyderabad
6     Bengaluru
7       Chennai
9     Hyderabad
10    Bengaluru
11      Unknown
12      Chennai
13    Hyderabad
Name: City, dtype: str

In [52]:
# price category for each unit price to know where outlier might have occured
def priceCategory(price):
    if pd.isna(price):
        return "Unknown"
    elif price < 1000:
        return "Low"
    elif price < 10000:
        return "Medium"
    else:
        return "High"

df["PriceCategory"] = df["UnitPrice"].apply(priceCategory)

print(df[["UnitPrice", "PriceCategory"]])

    UnitPrice PriceCategory
0       50000          High
1         500           Low
2        1200        Medium
3        8500        Medium
4       52000          High
5         500           Low
6        1200        Medium
7        8500        Medium
9       50000          High
10       2500        Medium
11       1800        Medium
12     999999          High
13       6500        Medium

In [54]:
# calcualte revewnue 
df["Revenue"] = df["Quantity"] * df["UnitPrice"]

print(df[["Product", "Quantity", "UnitPrice", "Revenue"]])

       Product  Quantity  UnitPrice   Revenue
0       Laptop       2.0      50000  100000.0
1        Mouse       5.0        500    2500.0
2     Keyboard       3.0       1200    3600.0
3      Monitor       2.0       8500   17000.0
4       Laptop       3.0      52000  156000.0
5        Mouse       4.0        500    2000.0
6     Keyboard       2.0       1200    2400.0
7      Monitor       3.0       8500   25500.0
9       Laptop       2.0      50000  100000.0
10  Headphones       3.0       2500    7500.0
11      Webcam       4.0       1800    7200.0
12        Desk       1.0     999999  999999.0
13       Chair       3.0       6500   19500.0

In [56]:
df

,OrderID,Product,City,Quantity,UnitPrice,OrderDate,product,PriceCategory,Revenue
0,O1001,Laptop,Chennai,2.0,50000,2026-10-01,Laptop,High,100000.0
1,O1002,Mouse,Chennai,5.0,500,2026-10-02,Mouse,Low,2500.0
2,O1003,Keyboard,Chennai,3.0,1200,2026-10-03,Keyboard,Medium,3600.0
3,O1004,Monitor,Bengaluru,2.0,8500,2026-10-04,Monitor,Medium,17000.0
4,O1005,Laptop,Chennai,3.0,52000,2026-10-05,Laptop,High,156000.0
5,O1006,Mouse,Hyderabad,4.0,500,2026-10-06,Mouse,Low,2000.0
6,O1007,Keyboard,Bengaluru,2.0,1200,2026-10-07,Keyboard,Medium,2400.0
7,O1008,Monitor,Chennai,3.0,8500,2026-10-08,Monitor,Medium,25500.0
9,O1010,Laptop,Hyderabad,2.0,50000,NaT,Laptop,High,100000.0
10,O1011,Headphones,Bengaluru,3.0,2500,2026-10-11,Headphones,Medium,7500.0
11,O1012,Webcam,Unknown,4.0,1800,2026-10-12,Webcam,Medium,7200.0
12,O1013,Desk,Chennai,1.0,999999,2026-10-13,Desk,High,999999.0
13,O1014,Chair,Hyderabad,3.0,6500,2026-10-14,Chair,Medium,19500.0

In [57]:
# save the new file csv
df.to_csv("sales_cleaned.csv", index=False)